14/01/22 (07:44:23) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:10) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:11) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:23) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:29) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:46) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:49) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:53) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:48:57) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:01) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:14) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:17) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:22) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:26) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:32) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:35) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (07:49:40) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (18:16:53) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
14/01/22 (18:17:30) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
15/01/22 (16:50:59) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
16/01/22 (05:13:19) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
16/01/22 (07:08:38) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
16/01/22 (18:09:44) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
16/01/22 (18:13:58) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
16/01/22 (18:16:25) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
16/01/22 (20:21:47) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
17/01/22 (05:58:38) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
17/01/22 (22:38:16) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
17/01/22 (22:38:26) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
18/01/22 (03:20:51) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
18/01/22 (03:21:07) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
19/01/22 (02:05:49) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
19/01/22 (05:12:07) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
19/01/22 (05:33:36) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
19/01/22 (19:03:31) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
19/01/22 (21:35:35) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
19/01/22 (22:47:33) | ERROR: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/koko/.config/bpytop/themes'
